.\" Copyright 2014 David Spencer, Baildon, West Yorkshire, U.K.
.\" All rights reserved.  For licence details, see the file 'LICENCE'.
.
.TH SLACKREPO.HINT 5 "2015-05-01" slackrepo-0.2.0
.
.
.
.SH NAME
slackrepo.hint \- slackrepo hintfile format
.
.
.
.SH SYNOPSIS
.BI /etc/slackrepo/ ID /hintfiles/ prgnam .hint
.br
where
.I ID
is 'SBo' by default.
.
.
.
.SH DESCRIPTION
.
A \(dqhintfile\(dq is a file that supplements a SlackBuild's .info file, for
example to specify options and additional dependencies, to override the version,
downloads and md5sums, etc.
.P
Each repository ID should have a local hintfiles directory, as configured
by the HINTDIR variable in the configuration file (see
.BR slackrepo.conf (5)).
By default this will be
.IR /etc/slackrepo/ID/hintfiles .
.P
The local hintfiles directory can optionally contain a structure of subdirectories
that is the same as the subdirectories in the SlackBuilds repository.
For example, if the SBo repository's SlackBuild file for wxPython is
.IR libraries/wxPython/wxPython.SlackBuild ,
then its hintfile would be
.IR /etc/slackrepo/SBo/hintfiles/libraries/wxPython/wxPython.hint .
Alternatively, hintfiles can be placed in the top level directory, for example
.IR /etc/slackrepo/SBo/hintfiles/wxPython.hint .
A hintfile in the top level directory takes precedence over a hintfile
of the same name in a subdirectory.
.P
Each repository ID should also have a default hint directory
for system supplied hintfiles,
as configured by the DEFAULT_HINTDIR variable
in the configuration file (see
.BR slackrepo.conf (5)).
For example, the SlackBuilds.org default hintfiles for Slackware 14.1 are
supplied in the directory
.IR /usr/share/slackrepo/SBo/default_hintfiles/14.1 .
The default hintfiles directory contains a structure of subdirectories
that is the same as the subdirectories in the SlackBuilds repository.
.P
Local hintfiles always take precedence over default hintfiles.
You can disable the default hintfile directory completely by unsetting the
DEFAULT_HINTDIR variable.
.P
The format of a hintfile is based on the format of SlackBuilds.org .info files,
but all the entries are optional, and any unrecognised entries are ignored.
The entries that can be defined are as follows:
.P
.RS
.EX
VERSION=\(dqnewversion\(dq
DOWNLOAD=\(dqnew urls\(dq
MD5SUM=\(dqnew md5sums\(dq
SHA256SUM=\(dqsha256sum\(dq
DOWNLOAD_arch=\(dqnew urls\(dq
MD5SUM_arch=\(dqnew md5sums\(dq
SHA256SUM_arch=\(dqsha256sum\(dq
ADDREQUIRES=\(dqadditional dependencies\(dq
OPTIONS=\(dqOPT1=yes OPT2=no ...\(dq
GROUPADD=\(dqgid:groupname ...\(dq
USERADD=\(dquid:username[:controlargs...] ...\(dq
SKIP=\(dqyesno\(dq
ARCH=\(dqarch\(dq
INSTALL=\(dqyesno\(dq
NUMJOBS=\(dq-j1\(dq
ANSWERS=\(dqstrings\(dq
CLEANUP=\(dqcommands\(dq
PRAGMA=\(dqpragmas\(dq
.EE
.RE
.
.
.
.SS VERSION=\(dqnewversion\(dq
.P
This hint can be specified to attempt an automatic patch of the version number
in both the SlackBuild and info files. The automatic patch is done by a simple text substitution.
This often won't work (particularly if the old version number is something like '1', or
if the download URL has not been patched correctly and you have not supplied a new
download URL in the hint file). The md5sum and/or sha256sum of the source archive will not be checked, unless you have
also supplied a new md5sum and/or sha256sum in the hint file. The patched SlackBuild and info
files are not kept.
.
.
.SS DOWNLOAD=\(dqnew urls\(dq
.P
This hint redefines download URLs that replace the URLs specified in the .info file,
for example if you have also defined VERSION=, or if the upstream URL has changed.
.P
However, if specified as
.BR DOWNLOAD=\(dqno\(dq ,
this hint indicates that the source needs
to be downloaded manually (for example, because of a licence agreement).
If you have already downloaded the source into the source cache, and if the
md5sum is correct, then the package will be built. Otherwise, a message will
be displayed explaining what you should do, and the package will be skipped.
.
.
.SS MD5SUM=\(dqnew md5sums\(dq
.P
This hint redefines md5sums that replace the md5sums specified in the .info file,
for example if you have also redefined VERSION=, or if the upstream source
archive has been changed.
.P
However, if specified as
.BR MD5SUM=\(dqno\(dq ,
this hint indicates that the source md5sums are not reliable
(for example, because of an unversioned archive) and should not be checked.
.
.
.SS SHA256SUM=\(dqsha256sums\(dq
.P
This hint specifies an sha256sum that will be checked (in addition to any md5sum).
.
.
.SS DOWNLOAD_arch=\(dqnew urls\(dq and MD5SUM_arch=\(dqnew md5sums\(dq and SHA256SUM_arch=\(dqsha256sums\(dq
.P
These hints redefine DOWNLOAD and MD5SUM, and specify SHA256SUM, as above,
for the specified arch.
.
.
.SS ADDREQUIRES=\(dqadditional dependencies\(dq
.P
This hint should define a list of dependencies, separated by spaces.
Dependencies in this list will be added to the dependencies defined by the
REQUIRES= list defined in the .info file. If the .info file specifies %README%,
you should set this hint (possibly as an empty string)
to stop slackrepo displaying a warning.
.
.
.SS OPTIONS=\(dqOPT1=yes OPT2=no ...\(dq
.P
This hint should define options described in the SlackBuild's README file.
Note that this is the only way in slackrepo that you can define SlackBuild options.
.
.
.SS GROUPADD=\(dqgid:groupname ...\(dq
.P
This hint defines groups to be added on the host system.
If a group already exists, nothing will be done.
If more than one group is to be added, a space-separated list can be specified.
Example:
.P
.RS
.EX
GROUPADD=\(dq209:postgres\(dq
.EE
.RE
.
.
.SS USERADD=\(dquid:username[:controlargs...] ...\(dq
.P
This hint defines usernames to be added on the host system.
If a username already exists, nothing will be done.
Optionally, additional control arguments of the useradd command can be
specified, separated by colons, with the space between the control argument
and its argument omitted. If more than one username is required, a
space-separated list of specifications can be defined.
Examples:
.P
.RS
.EX
USERADD=\(dq209:postgres:-d/var/lib/pgsql\(dq
USERADD=\(dq270:smtpd:-g0:-r:-s/bin/false:-d/var/empty 271:smtpq:-r:-s/bin/false:-d/var/empty\(dq
.EE
.RE
.P
.
.
.SS SKIP=\(dqyesno\(dq
.P
This hint can be specified if you want to skip the package when it
would otherwise be built, rebuilt, updated or removed.
If the hint isn't specified as SKIP=\(dqyes\(dq or SKIP=\(dqno\(dq, it will be interpreted
as \(dqyes\(dq, and the string will be displayed when the build is skipped, so that
you can put a helpful message into it, for example:
.P
.RS
.EX
SKIP=\(dqPlease remove the Slackware nc package before you build netcat-openbsd\(dq
.EE
.RE
.
.
.SS ARCH=\(dqarch\(dq
.P
This hint temporarily overrides the value of ARCH given in the configuration
file or environment.
This hint is most useful for SlackBuilds that repackage binaries.
.
.
.SS INSTALL=\(dqyesno\(dq
.P
This hint temporarily overrides the value of INSTALL given in the configuration
file or on the command line. Use this hint if you want a specific package to be
installed after it has been built (e.g. nvidia-driver). Note that if the control
argument --dry-run is specified, this hint will be ignored.
.
.
.SS NUMJOBS=\(dq-j1\(dq
.P
This hint temporarily overrides the value of NUMJOBS given in the configuration
file or environment. Use this hint if the build process fails when multiple
'make' jobs are used, so that the build will be executed with MAKEFLAGS='-j1'.
.
.
.SS ANSWERS=\(dqstring\(dq
.P
This hint can be specified if the build process wants to read answers to its
questions during execution, for example concerning a licence agreement.
The string is piped into the SlackBuild's standard input, so it should contain
whatever will make the build process happy. Newlines can be specified as \\n,
for example
.P
.RS
.EX
ANSWERS=\(dqok\\nyes\(dq
.EE
.RE
.
.
.SS CLEANUP=\(dqcommands\(dq
.P
This hint can be specified if the package needs extra cleanup when it is uninstalled
(e.g. packages that replace standard Slackware packages or install kernel modules).
The hint should define an appropriate shell command line.
to clean up after a kernel module is uninstalled:
.P
.RS
.EX
CLEANUP=\(dqdepmod -a\(dq
.EE
.RE
.P
For your convenience, slackrepo provides a command
.B s_reinstall
that reinstalls the specified Slackware packages, for example:
.P
.RS
.EX
CLEANUP=\(dqs_reinstall tetex tetex-doc\(dq
.EE
.RE
.
.
.SS PRAGMA=\(dqpragmas\(dq
This hint can be specified to perform one or more pragmas.
.B Pragmas are not guaranteed to work!
The hint name 'PRAGMA' used to be 'SPECIAL', which is still accepted as a synonym.
The following pragmas are available:
.P
.B multilib_ldflags
.P
On a multilib host, attempt to patch the SlackBuild to specify LDFLAGS,
as described in SlackBuilds.org FAQ 18.
.P
.B download_basename
.P
Provide a symlink for source downloads using the URL's basename,
for the benefit of SlackBuilds that don't expect content-disposition to be respected.
.P
.BR noexport_ARCH " and " noexport_BUILD " and " noexport_TAG
.P
Set ARCH or BUILD or TAG by patching the SlackBuild instead of exporting it
to the environment.
.P
.B unset_ARCH
.P
Unset the value of ARCH, overriding the value given in the configuration file
or environment.
Other variables can be specified, for example
.P
.RS
.EX
PRAGMA=\(dqunset_DISTCC_HOSTS\(dq
.EE
.RE
.P
.B noremove
.P
Do not remove (uninstall) packages before building the item.
This is particularly useful for gcc, glibc, etc.
.P
.B nofakeroot
.P
Override building the package as a non-root user with fakeroot.
Build the package as root, using
.BR sudo .
.P
.B no_make_test
.P
Patch the SlackBuild to comment out any 'make test' command.
.P
.B stubs-32
.P
Temporarily provide
.I /usr/include/gnu/stubs-32.h
as described in the memtest86+ README and xen SlackBuild.
.
.
.SH SEE ALSO
.
.BR slackrepo (8),
.BR slackrepo.conf (5),
.BR installpkg (8),
.BR upgradepkg (8),
.BR removepkg (8),
.BR pkgtool (8),
.BR slackpkg (8).
.
.
