#!/bin/bash
#-------------------------------------------------------------------------------
# SBoggit - automated clean (fsvo ;) building from SlackBuilds.org git
#
# Copyright 2013 David Spencer, Baildon, West Yorkshire, U.K.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#-------------------------------------------------------------------------------
#
[ $# = 0 ] && { echo 'Usage: SBoggit category|item ...'; exit 0; }
#
# Optional environment variables --
#   SBOGGIT - base directory, default /SBoggit
#   TAG - default _SBoggit
#   SBOREPO - local SBo git repo base, default $SBOGGIT/slackbuilds
#   GITBRANCH  - git branch to build in, default as follows:
gitstable='14.1'
#
# Possible hints in $SBOGGIT/hints/ --
#   prg.skipme - don't build prg (.skipme file contains optional comment for display/log)
#   prg.readmedeps - dependencies to substitute for %README% in REQUIRES="..."
#   prg.options - options to supply to the SlackBuild
#   prg.moredeps - more dependencies, eg. to support options
#   prg.uidgid - groupadd and useradd commands needed for prg [UNIMPLEMENTED]
#   prg.makej1 - set MAKEFLAGS='j1' during build
#   prg.tar.gz - SBo submission-style tarball to replace prg/* before build
#   prg.cleanup - script to run after prg is uninstalled [UNIMPLEMENTED]
#
# This script is intended to be run on a clean, full installation of Slackware.
#   Start with a full installation of Slackware.
#   Do not install any other packages.
#   Do not use the system for anything else.
#   Do a complete reinstall of Slackware after you have finished.
#
# Builds are not 100% clean and not 100% repeatable.  Each build is done as a
#   flat list of deps.  Each dep not already in $OUTREPO is built in the context
#   of the list, so it is possible for a package to pick up an unintended
#   dependency.  If one dep in the list is out of date, the remainder of the
#   list is rebuilt.  Git revision hashes are recorded in $OUTPUT, and rebuilds
#   are triggered when the hash in SBOREPO differs.
#
# The local git branch will be brutally cleaned on startup.  You have been
#   warned!  If no git repo is present, it will be cloned from SlackBuilds.org.
#   If the branch is '14.1' or 'master', it will be updated by fast forward
#   (if possible) from origin/master (which is probably SBo, but could be a
#   local mirror) if it is more than one day since the last update.
#-------------------------------------------------------------------------------

export SBOGGIT=${SBOGGIT:-/SBoggit}
export TAG=${TAG:-_SBoggit}
export SBOREPO=${SBOREPO:-$SBOGGIT/slackbuilds}
export GITBRANCH=${GITBRANCH:-$gitstable}

[ -d $SBOGGIT ] || { echo "ERROR: directory $SBOGGIT not found"; exit 1; }

export HINTS=$SBOGGIT/hints
export SRCDIR=$SBOGGIT/src
export OUTREPO=$SBOGGIT/output
export TMP=$SBOGGIT/tmp
export LOGDIR=$SBOGGIT/logs-$(date +%Y%m%d_%H%M)

if [ -z "$SLKARCH" ]; then
  case "$( uname -m )" in
    i?86) SLKARCH=i486 ;;
    arm*) SLKARCH=arm ;;
       *) SLKARCH=$( uname -m ) ;;
  esac
fi

#-------------------------------------------------------------------------------
# Initialisation
#-------------------------------------------------------------------------------

echo "Removing $TMP ..."
rm -rf $TMP
mkdir -p $HINTS $OUTREPO $TMP $SRCDIR
mkdir -p $LOGDIR/PASS $LOGDIR/FAIL
rm -f $LOGDIR/PASSLIST $LOGDIR/FAILLIST $LOGDIR/READMELIST
touch $LOGDIR/PASSLIST $LOGDIR/FAILLIST $LOGDIR/READMELIST

if [ -n "$(ls /var/log/packages/*$TAG 2>/dev/null)" ]; then
  echo "Removing all $TAG packages ..."
  removepkg /var/log/packages/*$TAG
  echo ""
fi

echo "Initialising git ..."
# This bit is going to be nasty, brutish and short :P
if [ ! -d $SBOREPO ]; then
  echo "$SBOREPO does not exist"
  git clone git://slackbuilds.org/slackbuilds.git $SBOREPO
  git checkout -b $gitstable -t origin/$gitstable
fi
cd $SBOREPO
git checkout -f $GITBRANCH
git reset --hard
git clean -xdf
if [ ( "$GITBRANCH" = 'master' -o "$GITBRANCH" = $gitstable ) \
     -a -n "$(find $SBOREPO/.git/FETCH_HEAD -mtime +1)" ]; then
  git fetch -a
  git merge --ff-only origin/$GITBRANCH
fi
echo "Finished initialising git."
echo ""

# Stolen from slackpkg :-)
for i in functions.d/*.sh; do
  if [ -x $i ]; then
    . $i
  fi
done

#-------------------------------------------------------------------------------

function buildzilla
{
  # Returns:
  # 1 - build failed
  # 2 - download failed
  # 3 - checksum failed
  # 4 - installpkg returned nonzero
  # 5 - skipped by hint, or unsupported on this arch
  # 6 - build returned 0 but nothing in $OUTPUT
  prg="$1"
  category=$(cd $SBOREPO/*/$prg/..; basename $(pwd))
  . $SBOREPO/$category/$prg/$prg.info
  unset BUILD
  buildassign=$(grep '^BUILD=' $SBOREPO/*/$PRGNAM/$PRGNAM.SlackBuild)
  eval $buildassign
  # At this point we have a full set of environment variables for called functions to use:
  # PRGNAM VERSION SLKARCH BUILD TAG DOWNLOAD* MD5SUM* etc

  msg="--$category/$prg-----------------------------------------------------------------------------"
  echo "${msg:0:79}"
  rm -f $LOGDIR/$prg.log

  if [ "$PRGNAM" != "$prg" ]; then
    echoyellow "WARNING: PRGNAM in $SBOREPO/$category/$prg/$prg.info is '$PRGNAM', not $prg"
  fi

  # Check whether the item should be skipped
  if [ -f $HINTS/$prg.skipme ]; then
    echoyellow "SKIPPED $category/$prg due to hint"
    cat $HINTS/$prg.skipme
    return 5
  fi

  # Get the source and symlink it into the SlackBuild directory
  if [ -d $SRCDIR/$prg ]; then
    if ! checksrc ; then
      echo "Note: bad checksums in cached source, will download again"
      downloadsrc
      case $? in
        0) checksrc || { savebadsrc; itfailed; return 3; } ;;
        2) rm -rf $SRCDIR/$prg;  return 5 ;;
        *) savebadsrc; itfailed; return 2 ;;
      esac
    fi
  else
    downloadsrc
    case $? in
      0) checksrc || { savebadsrc; itfailed; return 3; } ;;
      2) rm -rf $SRCDIR/$prg;  return 5 ;;
      *) savebadsrc; itfailed; return 2 ;;
    esac
  fi
  ln -sf -t $SBOREPO/$category/$prg/ $SRCDIR/$prg/*

  # Get any hints for the build
  if [ -f $HINTS/$prg.options ]; then
    options="$(cat $HINTS/$prg.options)"
    echo "Hint: found options $options"
  fi
  tempmakeflags=''
  if [ -f $HINTS/$prg.makej1 ]; then
    tempmakeflags="MAKEFLAGS='-j1'"
    echo "Hint: setting $tempmakeflags"
  fi

  # Build it
  echo "SlackBuilding $prg.SlackBuild ..."
  export OUTPUT=$OUTREPO/$prg
  rm -rf $OUTPUT/*
  mkdir -p $OUTPUT
  ( cd $SBOREPO/$category/$prg; env $tempmakeflags $options sh ./$prg.SlackBuild ) >>$LOGDIR/$prg.log 2>&1
  stat=$?
  if [ $stat != 0 ]; then
    echo "ERROR: $prg.SlackBuild failed (status $stat)"
    itfailed
    return 1
  fi

  # Make sure we got something :-)
  pkglist=$(ls $OUTPUT/*.t?z 2>/dev/null)
  if [ -z "$pkglist" ]; then
    echo "ERROR: no packages found in $OUTPUT"
    itfailed
    return 6
  fi

  # Install the built packages
  # (this supports multiple output packages because some Slackware SlackBuilds do that)
  for pkgpath in $pkglist; do
    # This is our best chance to verify the package name:
    pkg=$(basename $pkgpath)
    case $pkg in
    $PRGNAM-${VERSION}-$SLKARCH-$BUILD$TAG.t?z | \
    $PRGNAM-${VERSION}-noarch-$BUILD$TAG.t?z | \
    $PRGNAM-${VERSION}_*-$SLKARCH-$BUILD$TAG.t?z | \
    $PRGNAM-${VERSION}_*-noarch-$BUILD$TAG.t?z )
      : ;;
    *)
      echoyellow "WARNING: abnormal package name $pkg"
      pprgnam=$(echo $pkg | rev | cut -f4- -d- | rev)
      pversion=$(echo $pkg | rev | cut -f3 -d- | rev)
      parch=$(echo $pkg | rev | cut -f2 -d- | rev)
      pbuild=$(echo $pkg | rev | cut -f1 -d- | rev | sed 's/[^0-9]*$//')
      ptag=$(echo $pkg | rev | cut -f1 -d- | rev | sed 's/^[0-9]*//' | sed 's/\..*$//')
      pext=$(echo $pkg | rev | cut -f1 -d- | rev | sed 's/^[0-9]*//' | sed 's/^.*\.//')
      [  "$pprgnam" != "$PRGNAM"  ] && echoyellow "PRGNAM is $pprgnam not $PRGNAM"
      [ "$pversion" != "$VERSION" ] && echoyellow "VERSION is $pversion not $VERSION"
      [    "$parch" != "$SLKARCH" -a "$parch" != "noarch" ] && \
        echoyellow "ARCH is $parch not $SLKARCH or noarch"
      [   "$pbuild" != "$BUILD"   ] && echoyellow "BUILD is $pbuild not $BUILD"
      [     "$ptag" != "$TAG"     ] && echoyellow "TAG is $ptag not $TAG"
      [ "$pext" != 'tgz' -a "$pext" != 'tbz' -a "$pext" != 'tlz' -a "$pext" != 'txz' ] && \
        echoyellow "Suffix .$pext is not .t[gblx]z"
      ;;
    esac 
    echo "Installing $pkgpath ..."
    installpkg --terse $pkgpath
    stat=$?
    if [ $stat != 0 ]; then
      echo "ERROR: installpkg $pkgpath failed (status $stat)"
      itfailed
      return 4
    fi
    dotprofilizer $pkg
  done

  itpassed  # \o/
  return 0
}

#-------------------------------------------------------------------------------

function dependublaster2000
{
  local me="$1"
  local prevdep mydeps moredeps dep readmedep
  for prevdep in $DEPLIST; do
    if [ "$prevdep" = "$me" ]; then
      # if I'm already on the list, then my deps must also be on the list
      # so nothing to do :-)
      return 0
    fi
  done
  if [ ! -d $SBOREPO/*/$me ]; then
    echoyellow "WARNING: Dependency $me not found in $SBOREPO"
    return 0  # carry on regardless ;-)
  fi
  if [ -f $HINTS/$me.tar.gz ]; then
    echo "Hint: applying tarball for $me"
    ( cd $SBOREPO/*/$me/..; rm -rf $me/; tar xf $HINTS/$me.tar.gz )
  fi
  . $SBOREPO/*/$me/$me.info
  # ok, ready to go!  First, add my deps:
  mydeps="$REQUIRES"
  if [ -f $HINTS/$me.moredeps ]; then
    moredeps="$(cat $HINTS/$me.moredeps)"
    echo "Hint: adding more deps: $moredeps"
    mydeps="$mydeps $moredeps"
  fi
  for dep in $mydeps; do
    if [ $dep = '%README%' ]; then
      if [ -f $HINTS/$me.readmedeps ]; then
        echo "Hint: substituting '$(cat $HINTS/$me.readmedeps)' for %README%"
        for readmedep in $(cat $HINTS/$me.readmedeps); do 
          dependublaster2000 $readmedep
        done
      else
        echoyellow "WARNING: %README% in $me.info but $HINTS/$me.readmedeps not found"
      fi
    else
      dependublaster2000 $dep
    fi
  done
  # then add me:
  DEPLIST="$DEPLIST $me"
  return 0
}

#-------------------------------------------------------------------------------
# Main loop
#-------------------------------------------------------------------------------

while [ $# != 0 ]; do

  ARG=${1%%/}; shift

  # Check the current argument
  if [ -d $SBOREPO/${ARG##*/} ]; then
    # it's a category: expand it into a list of its items
    set -- $SBOREPO/$ARG/* "$@"
    continue
  fi
  # otherwise, the last component should be an item
  PRG=$(basename ${ARG%%/})
  if [ ! -d $SBOREPO/*/$PRG ]; then
    echoinbox "ERROR: $PRG is neither a category nor an application"
    continue
  fi
  CATEGORY=$(cd $SBOREPO/*/$PRG/..; basename $(pwd))
  echoinbox "$CATEGORY/$PRG"

  # Quick check whether the item should be skipped
  if [ -f $HINTS/$PRG.skipme ]; then
    echoyellow "SKIPPED $CATEGORY/$PRG due to hint"
    cat $HINTS/$PRG.skipme
    if inOUTREPOanduptodate $PRG; then
      echo "Note: previously built $CATEGORY/$PRG is up-to-date"
    fi
    echo ""
    continue
  fi

  # Work out dependencies (DEPLIST), and then which deps are already up-to-date
  # and can just be installed (INSTLIST) and which deps need to be built (TODOLIST)
  export DEPLIST=""
  dependublaster2000 $PRG
  if [ "$(echo $DEPLIST)" != "$PRG" ]; then
    echo "Package stack for $PRG:" $DEPLIST
  fi
  INSTLIST=""
  TODOLIST=""
  needbuild='n'
  for dep in $DEPLIST; do
    if inOUTREPOanduptodate $dep; then
      if [ $needbuild = 'y' ]; then
        TODOLIST=$(echo $TODOLIST $dep)
      else
        INSTLIST=$(echo $INSTLIST $dep)
      fi
    else
      # trigger build for all following deps, even if they are already in OUTREPO
      needbuild='y'
      TODOLIST=$(echo $TODOLIST $dep)
    fi
  done

  # Process INSTLIST and TODOLIST
  # If there's nothing in TODOLIST, don't bother installing :D
  if [ "$TODOLIST" != '' ]; then
    if [ "$TODOLIST" != "$PRG" ]; then
      echo "To-do list for $PRG:" $DEPLIST
    fi
    instok='y'
    for instprg in $INSTLIST; do
      installfromOUTREPO $instprg
      if [ $? != 0 ]; then
        instok='n'
        [ $instprg != $PRG ] && echored "ABORTED $CATEGORY/$PRG"
        break
      fi
    done
    if [ $instok = 'y' ]; then
      for todoprg in $TODOLIST; do
        buildzilla $todoprg
        if [ $? != 0 ]; then
          [ $todoprg != $PRG ] && echored "ABORTED $CATEGORY/$PRG"
          break
        fi
      done
    fi
    echo "-------------------------------------------------------------------------------"
    echo "Removing all $TAG packages ..."
    removepkg /var/log/packages/*$TAG >/dev/null 2>&1
    # undo any clever things that a profile.d script might have set
    unset LD_PRELOAD JAVA_HOME
  fi
  echo ""

done

exit 0
